### ISSUE TITLE
アプリ用アイコン、Web用Favicon作成

### ISSUE THREAD

**Issue by FltSv** [FltSv/GalleryFound#28]

**Comment by kurokoutsuki** [comment]
こんなんでどうかな

![スクリーンショット 2023-12-16 12 36 56](https://github.com/FltSv/GalleryFound/assets/148703705/85d18983-b56c-46cc-85a3-4f839c51c9c2)

**Comment by FltSv** [comment]
良いと思います！！
イラスト完成したらfaviconとして設定するのもお願いできますでしょうか？


> こんなんでどうかな
> 
> ![スクリーンショット 2023-12-16 12 36 56](https://private-user-images.githubusercontent.com/148703705/290968373-85d18983-b56c-46cc-85a3-4f839c51c9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2OTg1MjIsIm5iZiI6MTcwMjY5ODIyMiwicGF0aCI6Ii8xNDg3MDM3MDUvMjkwOTY4MzczLTg1ZDE4OTgzLWI1NmMtNDZjYy04NWEzLTRmODM5YzUxYzljMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQwMzQzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWJiYzhkNmYzZWI5YmY5ZTYwMjY1ZWQ0MDE3MWU5ZDc4YzZmZmFhMWUzNGQ4MjE0MDJmODdlZDI4MjQzZTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gxH39BPy327Cve-kSh-ihaQ8m41DprwvGGeoe4ud6MY)

**Comment by kurokoutsuki** [comment]
了解です！！
